# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# The title of your site
title: Admanus Group

# The email address for site-related communication
email: admin@admanus.com

# A brief description of your site
description: >- # this means to ignore newlines until "baseurl:"
  Bridging individual skills and knowledge to create a dynamic and effective collaborative network.

# The subpath of your site, e.g. /blog
baseurl: ""

# The base hostname & protocol for your site, e.g. http://example.com
url: ""

# Your GitLab username
gitlab_username: nairuby

# Your GitHub username
github_username: nairuby

# The current year
current_year: 2025

# Build settings
markdown: kramdown

# Plugins to use with Jekyll
plugins:
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-assets

# Asset settings
assets:
  debug: false
  compress:
    css:
      development: false
      production: true
    js:
      development: true
      production: true
  js_compressor: uglifier
  css_compressor: sass
  sources:
    - _assets/javascripts
    - _assets/stylesheets

# Collections of content
collections:
  members:
    output: true
    permalink: /members/:name/
  groups:
    output: true
    permalink: /groups/:name/
  projects:
    output: true
    permalink: /projects/:name


# Minifier settings
minifier:
  css:
    compress: true
    preserve_comments: false
    preserve_hacks: true
    remove_inlined_files: true
  js:
    compress: true
    mangle: true
    output_opts:
      max_line_len: 32000
      beautify: false
    mangle_opts:
      toplevel: true
  html:
    remove_comments: true
    remove_empty_lines: true
    remove_blank_attributes: true
    remove_optional_tags: true
    collapse_whitespace: true
    conservative_collapse: true
    minify_js: true
    minify_css: true
    remove_quotes: true
    remove_http_protocol: true
    remove_https_protocol: true
    remove_script_attributes: true
    remove_style_attributes: true
    simple_doctype: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - 2017speakers/
  - Makefile
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
