# docker run --rm --volume="$PWD:/srv/jekyll" -p 4000:4000 jekyll/jekyll:4.0 jekyll serve
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:slim
    #build: .
    ports:
      - 8001:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
