name: Deploy site

on:
  push:
    branches:
      - main
    paths:
      - "assets/**"
      - "documents/**"
      - "fonts/**"
      - "images/**"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "Gemfile"
      - "Gemfile.lock"
      - "!README.md"
  pull_request:
    branches:
      - main
    paths:
      - "assets/**"
      - "documents/**"
      - "fonts/**"
      - "images/**"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "Gemfile"
      - "Gemfile.lock"
      - "!README.md"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    # available images: https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
          bundler-cache: true
      - name: Update _config.yml ⚙️
        uses: fjogeleit/yaml-update-action@main
        with:
          commitChange: false
          valueFile: "_config.yml"
          propertyPath: "giscus.repo"
          value: ${{ github.repository }}
      - name: Sync Google Sheets and Generate Files 🔄
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          APPLICATION_NAME: JekyllDataImporter
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          SHEET1_FILENAME: members
          SHEET1_NAME: members
          SHEET1_IMAGE_COLUMN: image
          SHEET1_IMAGE_SUBDIR: remote_members
          SHEET2_FILENAME: groups
          SHEET2_NAME: groups
          SHEET2_IMAGE_COLUMN: image
          SHEET2_IMAGE_SUBDIR: remote_groups
          SHEET3_FILENAME: projects
          SHEET3_NAME: projects
          SHEET3_IMAGE_COLUMN: image
          SHEET3_IMAGE_SUBDIR: remote_groups
          SHEET4_FILENAME: project_contributors
          SHEET4_NAME: project_contributors
        run: |
          ruby _build/sync_google_sheets.rb
          make generate

      - name: Install and Build 🔧
        run: |
          make build
      - name: Purge unused CSS 🧹
        run: |
          npm install -g purgecss
          purgecss -c purgecss.config.js
      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
